spring:
  http:
    encoding:
      charset: UTF-8
  datasource:
    driverClassName: org.postgresql.Driver
    username: daimoncool
    password: Pavilion23xi
    url: jdbc:postgresql://aws-daimon-db.c7flxk5cyw0g.us-east-2.rds-preview.amazonaws.com:5432/daimon_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        physical_naming_strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
        jdbc:
          time_zone: UTC
        ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/daimon.p12
    key-store-password: Pavilion23xi
    key-alias: daimon
#  http:
#    port:
#      8080